### PR TITLE
Add style to 'main-image'

### PR DESCRIPTION
**Pull request by solidocean007**
On my large monitor the image was out of proportion.  It was because the width was 100% while the height was fixed at 500px.  I changed it to be more responsive to a larger monitor.  I also used format 'prettier' to add correct indentations.

### CODE REVIEW

**Review by jh115424 — APPROVED** [review]
I do see how you changed the width and height set to auto.  
 How can you know what number to have to make sure it is responsive to different size monitors?

**Comment by JoshuaWoodsdev** [comment]
Hmmm IDK what to do next

**Comment by solidocean007** [comment]
> I do see how you changed the width and height set to auto. How can you know what number to have to make sure it is responsive to different size monitors?

I didn't really make it responsive for all monitors.  We can do that next if you like.   I just removed the fixed height with 100% width so the image would scale.

**Comment by solidocean007** [comment]
> Hmmm IDK what to do next

Maybe you can make the page tablet/mobile responsive?

**Comment by jh115424** [comment]
> Hmmm IDK what to do next

I guess we can add more to the page.   I can start with something,

**Comment by JoshuaWoodsdev** [comment]
I'm going to clone the project

**Comment by JoshuaWoodsdev** [comment]
Sorry been late on my end I'll catch up today

**Comment by jh115424** [comment]
[like]  Jennifer Hodge reacted to your message:
________________________________

**Pull request merged**
